export const defaultCrmSequences = [
  {
    audience: 'lead',
    key: 'lead-intake-follow-up',
    name: 'Lead intake follow-up',
    status: 'active',
    steps: [
      {
        delayAmount: 2,
        delayUnit: 'hours',
        emailSubject: 'Checking in on your Grime Time request',
        emailTemplateKey: 'lead_follow_up',
        internalNotes: 'Light-touch follow-up after the inbound request lands.',
        stepType: 'send_email',
      },
      {
        delayAmount: 1,
        delayUnit: 'days',
        internalNotes: 'If there is still no response, make sure the queue keeps moving.',
        stepType: 'create_task',
        taskPriority: 'medium',
        taskTitle: 'Follow up new lead',
        taskType: 'general',
      },
    ],
    trigger: 'lead_created',
  },
  {
    audience: 'opportunity',
    key: 'quote-sent-follow-up',
    name: 'Quote sent follow-up',
    status: 'active',
    steps: [
      {
        delayAmount: 2,
        delayUnit: 'days',
        internalNotes: 'Give the customer a short review window before the first follow-up.',
        stepType: 'wait',
      },
      {
        delayAmount: 0,
        delayUnit: 'days',
        emailSubject: 'Checking in on your Grime Time estimate',
        emailTemplateKey: 'quote_follow_up',
        internalNotes: 'Prompt the customer to reply or book the next step.',
        stepType: 'send_email',
      },
      {
        delayAmount: 2,
        delayUnit: 'days',
        internalNotes: 'If there is still no movement, create an internal follow-up task.',
        stepType: 'create_task',
        taskPriority: 'high',
        taskTitle: 'Call on sent quote',
        taskType: 'quote_follow_up',
      },
    ],
    trigger: 'quote_sent',
  },
  {
    audience: 'billing',
    key: 'invoice-issued-reminder',
    name: 'Invoice issued reminder',
    status: 'active',
    steps: [
      {
        delayAmount: 5,
        delayUnit: 'days',
        internalNotes: 'Friendly reminder before the invoice slips overdue.',
        stepType: 'wait',
      },
      {
        delayAmount: 0,
        delayUnit: 'days',
        emailSubject: 'Reminder: invoice from Grime Time',
        emailTemplateKey: 'invoice_reminder',
        internalNotes: 'Customer-facing reminder with portal/payment link.',
        stepType: 'send_email',
      },
      {
        delayAmount: 2,
        delayUnit: 'days',
        internalNotes: 'Create a staff billing task if payment is still pending.',
        stepType: 'create_task',
        taskPriority: 'high',
        taskTitle: 'Review unpaid invoice',
        taskType: 'billing_follow_up',
      },
    ],
    trigger: 'invoice_issued',
  },
  {
    audience: 'billing',
    key: 'invoice-overdue-escalation',
    name: 'Invoice overdue escalation',
    status: 'active',
    steps: [
      {
        delayAmount: 0,
        delayUnit: 'days',
        emailSubject: 'Past due invoice from Grime Time',
        emailTemplateKey: 'invoice_overdue',
        internalNotes: 'Immediate overdue notice after the invoice crosses terms.',
        stepType: 'send_email',
      },
      {
        delayAmount: 1,
        delayUnit: 'days',
        internalNotes: 'Push a billing task back into the queue right away.',
        stepType: 'create_task',
        taskPriority: 'urgent',
        taskTitle: 'Resolve overdue invoice',
        taskType: 'billing_follow_up',
      },
    ],
    trigger: 'invoice_overdue',
  },
  {
    audience: 'customer',
    key: 'post-service-follow-up',
    name: 'Post-service follow-up',
    status: 'active',
    steps: [
      {
        delayAmount: 1,
        delayUnit: 'days',
        internalNotes: 'Short thank-you and check-in after completed service.',
        stepType: 'wait',
      },
      {
        delayAmount: 0,
        delayUnit: 'days',
        emailSubject: 'How did the service go?',
        emailTemplateKey: 'service_follow_up',
        internalNotes: 'Invite the customer to review the completed work and reply with any concerns.',
        stepType: 'send_email',
      },
    ],
    trigger: 'job_completed',
  },
] as const
