/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    quotes: Quote;
    users: User;
    invoices: Invoice;
    'service-plans': ServicePlan;
    'service-appointments': ServiceAppointment;
    'growth-milestones': GrowthMilestone;
    'ops-asset-ladder-items': OpsAssetLadderItem;
    'ops-liability-items': OpsLiabilityItem;
    'ops-scorecard-rows': OpsScorecardRow;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    quotes: QuotesSelect<false> | QuotesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    invoices: InvoicesSelect<false> | InvoicesSelect<true>;
    'service-plans': ServicePlansSelect<false> | ServicePlansSelect<true>;
    'service-appointments': ServiceAppointmentsSelect<false> | ServiceAppointmentsSelect<true>;
    'growth-milestones': GrowthMilestonesSelect<false> | GrowthMilestonesSelect<true>;
    'ops-asset-ladder-items': OpsAssetLadderItemsSelect<false> | OpsAssetLadderItemsSelect<true>;
    'ops-liability-items': OpsLiabilityItemsSelect<false> | OpsLiabilityItemsSelect<true>;
    'ops-scorecard-rows': OpsScorecardRowsSelect<false> | OpsScorecardRowsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    pricing: Pricing;
    internalOpsSettings: InternalOpsSetting;
    quoteSettings: QuoteSetting;
    servicePlanSettings: ServicePlanSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
    internalOpsSettings: InternalOpsSettingsSelect<false> | InternalOpsSettingsSelect<true>;
    quoteSettings: QuoteSettingsSelect<false> | QuoteSettingsSelect<true>;
    servicePlanSettings: ServicePlanSettingsSelect<false> | ServicePlanSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: number | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (number | null) | Media;
  };
  layout: (
    | ServiceGridBlock
    | PricingTableBlock
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (number | Post)[] | null;
  categories?: (number | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (number | null) | Category;
  breadcrumbs?:
    | {
        doc?: (number | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  phone?: string | null;
  company?: string | null;
  billingAddress?: {
    street1?: string | null;
    street2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
  };
  serviceAddress?: {
    street1?: string | null;
    street2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
  };
  roles: ('admin' | 'customer')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceGridBlock".
 */
export interface ServiceGridBlock {
  heading: string;
  intro?: string | null;
  services?:
    | {
        name: string;
        summary: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'serviceGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingTableBlock".
 */
export interface PricingTableBlock {
  /**
   * Optional title for this section. If empty, uses the global “Pricing & packages” title when source is global.
   */
  heading?: string | null;
  dataSource?: ('global' | 'inline') | null;
  inlinePlans?:
    | {
        /**
         * Package name, e.g. “Driveway refresh”
         */
        name: string;
        /**
         * Short subtitle under the name
         */
        tagline?: string | null;
        /**
         * Display price, e.g. $199, From $149, Call for quote
         */
        price: string;
        /**
         * Fine print: per visit, typical home size, etc.
         */
        priceNote?: string | null;
        highlighted?: boolean | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricingTable';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (number | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: number | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: number | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Internal job quotes only. Includes line items, totals, and Texas tax review fields. Never expose draft quotes on the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes".
 */
export interface Quote {
  id: number;
  /**
   * Short label, for example: 123 Oak - house wash
   */
  title: string;
  status?: ('draft' | 'sent' | 'accepted' | 'lost') | null;
  validUntil?: string | null;
  customerName?: string | null;
  customerEmail?: string | null;
  customerPhone?: string | null;
  /**
   * Attach the customer portal account so the estimate appears in their portal.
   */
  customerUser?: (number | null) | User;
  /**
   * Job site details used for scoping and local tax review.
   */
  serviceAddress?: {
    street1?: string | null;
    street2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
  };
  propertyType?: ('residential' | 'commercial' | 'new_residential_construction' | 'hoa_multi_unit' | 'other') | null;
  /**
   * Sq ft, stories, linear feet, or preset label.
   */
  jobSize?: string | null;
  /**
   * Surfaces: siding, concrete, roof, windows, gutters, fencing, etc.
   */
  surfaceDescription?: string | null;
  soilingLevel?: ('light' | 'medium' | 'heavy') | null;
  /**
   * Ladder work, vegetation, HOA restrictions, hazards, water access, etc.
   */
  accessNotes?: string | null;
  /**
   * Quote builder rows. Totals are calculated from these lines.
   */
  serviceLines?:
    | {
        serviceType:
          | 'house_wash'
          | 'soft_wash'
          | 'roof_cleaning'
          | 'window_cleaning'
          | 'concrete_cleaning'
          | 'driveway_walkway_cleaning'
          | 'fence_cleaning'
          | 'deck_patio_cleaning'
          | 'gutter_cleaning'
          | 'rust_stain_treatment'
          | 'other';
        description: string;
        quantity: number;
        unit?: string | null;
        unitPrice: number;
        lineTotal?: number | null;
        /**
         * Most Texas exterior cleaning lines will stay taxable unless you have a documented exception.
         */
        taxable?: boolean | null;
        taxCategory?:
          | ('building_grounds_cleaning' | 'pressure_washing_maintenance' | 'window_washing' | 'manual_review_required')
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Calculated subtotal and tax fields. Enter the rate you plan to collect; keep exemptions and CPA-review paths documented.
   */
  pricing?: {
    /**
     * Pre-tax discount applied against the quote subtotal.
     */
    discountAmount?: number | null;
    /**
     * Texas Comptroller guidance generally treats cleaning homes/buildings, washing windows, and pressure washing buildings, sidewalks, or parking lots as taxable. Keep exemption and CPA-review paths available before finalizing the quote.
     */
    taxDecision?:
      | ('collect_sales_tax' | 'homebuilder_exception' | 'exemption_certificate' | 'manual_review_required')
      | null;
    /**
     * Enter the actual rate you plan to collect. Texas state sales tax is 6.25%; local tax can bring the total up to 8.25% depending on your facts and filing setup.
     */
    taxRatePercent?: number | null;
    /**
     * Document why you collected or did not collect tax, plus any homebuilder certification, exemption certificate, or CPA guidance.
     */
    taxDecisionNotes?: string | null;
    subtotal?: number | null;
    taxableSubtotal?: number | null;
    salesTaxAmount?: number | null;
    total?: number | null;
  };
  /**
   * Staff-only pricing discussion, objections, follow-up notes, and compliance flags.
   */
  internalNotes?: string | null;
  /**
   * Optional lead form submission this quote came from.
   */
  sourceSubmission?: (number | null) | FormSubmission;
  /**
   * Mirror status for the active CRM deal sync.
   */
  crm?: {
    provider?: ('engagebay' | 'hubspot') | null;
    dealId?: string | null;
    syncStatus?:
      | ('skipped_draft' | 'skipped_no_email' | 'skipped_provider' | 'ok' | 'ok_note_warning' | 'failed')
      | null;
    syncedAt?: string | null;
    syncDetail?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Website form posts. Lead columns are derived from field names (email, name, etc.). CRM columns reflect provider sync.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Auto-filled from submission row named email (or similar).
   */
  leadEmail?: string | null;
  /**
   * Auto-filled from name / fullName / firstName rows.
   */
  leadName?: string | null;
  /**
   * CRM sync result (server-set).
   */
  crmSyncStatus?:
    | (
        | 'ok'
        | 'ok_note_warning'
        | 'failed'
        | 'failed_contact'
        | 'skipped_no_api_key'
        | 'skipped_sync_disabled'
        | 'skipped_no_email'
        | 'skipped_no_rows'
      )
    | null;
  /**
   * ISO timestamp of last CRM sync attempt.
   */
  crmSyncedAt?: string | null;
  /**
   * Error or status detail from the sync step.
   */
  crmSyncDetail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer-facing invoices that appear in the portal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices".
 */
export interface Invoice {
  id: number;
  invoiceNumber: string;
  title: string;
  status: 'draft' | 'open' | 'paid' | 'overdue' | 'void';
  issueDate?: string | null;
  dueDate?: string | null;
  customerUser?: (number | null) | User;
  customerEmail: string;
  customerName?: string | null;
  serviceAddress?: {
    street1?: string | null;
    street2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
  };
  total: number;
  balanceDue: number;
  /**
   * Optional hosted invoice / payment URL.
   */
  paymentUrl?: string | null;
  lineItems?:
    | {
        description: string;
        amount: number;
        id?: string | null;
      }[]
    | null;
  relatedQuote?: (number | null) | Quote;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Recurring maintenance-plan records used by the customer portal and scheduling views.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-plans".
 */
export interface ServicePlan {
  id: number;
  title: string;
  status: 'draft' | 'active' | 'paused' | 'cancelled';
  /**
   * First visit or anchor date used to suggest the ongoing cadence.
   */
  anchorDate?: string | null;
  preferredWindow?: ('morning' | 'afternoon' | 'flexible') | null;
  customerUser: number | User;
  customerEmail: string;
  customerName?: string | null;
  serviceAddress?: {
    street1?: string | null;
    street2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
  };
  /**
   * Accepted quote this plan was built from.
   */
  sourceQuote?: (number | null) | Quote;
  /**
   * Short service scope summary shown in the portal.
   */
  serviceSummary?: string | null;
  /**
   * Reference price for one normal standalone visit.
   */
  singleJobAmount: number;
  discountPercent: number;
  visitsPerYear: number;
  billingInstallmentsPerYear: number;
  discountedVisitAmount?: number | null;
  annualPlanAmount?: number | null;
  installmentAmount?: number | null;
  cadenceMonths?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Scheduled or requested customer jobs shown in the portal and ops calendar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-appointments".
 */
export interface ServiceAppointment {
  id: number;
  title: string;
  status: 'requested' | 'confirmed' | 'reschedule_requested' | 'completed' | 'cancelled';
  arrivalWindow?: ('morning' | 'afternoon' | 'flexible') | null;
  requestSource?: ('portal' | 'admin' | 'phone' | 'subscription_auto') | null;
  customerUser: number | User;
  customerEmail: string;
  customerName?: string | null;
  serviceAddress?: {
    street1?: string | null;
    street2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
  };
  /**
   * Customer-requested date before the team confirms the slot.
   */
  requestedDate?: string | null;
  scheduledStart?: string | null;
  scheduledEnd?: string | null;
  relatedQuote?: (number | null) | Quote;
  servicePlan?: (number | null) | ServicePlan;
  customerNotes?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Growth ladder rows shown on /ops (edit in admin).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "growth-milestones".
 */
export interface GrowthMilestone {
  id: number;
  title: string;
  /**
   * Volume or stage trigger (e.g. jobs per month).
   */
  trigger?: string | null;
  /**
   * Operating standard to unlock the next stage.
   */
  winCondition?: string | null;
  /**
   * Lower numbers appear first on the portal.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Equipment ladder on /ops. Unchecked = want; checked = have.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ops-asset-ladder-items".
 */
export interface OpsAssetLadderItem {
  id: number;
  /**
   * Stage or category name.
   */
  label: string;
  /**
   * What to buy or spec.
   */
  buyNotes?: string | null;
  /**
   * Why it matters / bottleneck it removes.
   */
  whyNotes?: string | null;
  /**
   * Checked = you have it. Unchecked = on the wishlist.
   */
  owned?: boolean | null;
  /**
   * Lower numbers appear first on the portal.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Liability / drag items shown on /ops scorecard tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ops-liability-items".
 */
export interface OpsLiabilityItem {
  id: number;
  label: string;
  /**
   * Optional detail shown in the portal sheet.
   */
  notes?: string | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * KPI definitions for /ops. Title should match the built-in KPI name (e.g. Revenue, MRR) to override defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ops-scorecard-rows".
 */
export interface OpsScorecardRow {
  id: number;
  /**
   * Must match scorecard KPI label exactly when overriding defaults.
   */
  title: string;
  formula: string;
  /**
   * Target / operating standard text.
   */
  targetGuidance?: string | null;
  /**
   * Optional scalar staff can track (displayed on /ops card grid).
   */
  manualValue?: number | null;
  /**
   * Label for manual value (e.g. Target hours).
   */
  manualValueLabel?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: number | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  categories?: {
    /**
     * Allow clients to find categories.
     */
    find?: boolean | null;
    /**
     * Allow clients to create categories.
     */
    create?: boolean | null;
    /**
     * Allow clients to update categories.
     */
    update?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
    /**
     * Allow clients to update media.
     */
    update?: boolean | null;
  };
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
  };
  posts?: {
    /**
     * Allow clients to find posts.
     */
    find?: boolean | null;
    /**
     * Allow clients to create posts.
     */
    create?: boolean | null;
    /**
     * Allow clients to update posts.
     */
    update?: boolean | null;
  };
  quotes?: {
    /**
     * Allow clients to find quotes.
     */
    find?: boolean | null;
  };
  footer?: {
    /**
     * Allow clients to find footer global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update footer global.
     */
    update?: boolean | null;
  };
  header?: {
    /**
     * Allow clients to find header global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update header global.
     */
    update?: boolean | null;
  };
  pricing?: {
    /**
     * Allow clients to find pricing global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update pricing global.
     */
    update?: boolean | null;
  };
  quoteSettings?: {
    /**
     * Allow clients to find quoteSettings global.
     */
    find?: boolean | null;
    /**
     * Allow clients to update quoteSettings global.
     */
    update?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'quotes';
        value: number | Quote;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'invoices';
        value: number | Invoice;
      } | null)
    | ({
        relationTo: 'service-plans';
        value: number | ServicePlan;
      } | null)
    | ({
        relationTo: 'service-appointments';
        value: number | ServiceAppointment;
      } | null)
    | ({
        relationTo: 'growth-milestones';
        value: number | GrowthMilestone;
      } | null)
    | ({
        relationTo: 'ops-asset-ladder-items';
        value: number | OpsAssetLadderItem;
      } | null)
    | ({
        relationTo: 'ops-liability-items';
        value: number | OpsLiabilityItem;
      } | null)
    | ({
        relationTo: 'ops-scorecard-rows';
        value: number | OpsScorecardRow;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        serviceGrid?: T | ServiceGridBlockSelect<T>;
        pricingTable?: T | PricingTableBlockSelect<T>;
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ServiceGridBlock_select".
 */
export interface ServiceGridBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  services?:
    | T
    | {
        name?: T;
        summary?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PricingTableBlock_select".
 */
export interface PricingTableBlockSelect<T extends boolean = true> {
  heading?: T;
  dataSource?: T;
  inlinePlans?:
    | T
    | {
        name?: T;
        tagline?: T;
        price?: T;
        priceNote?: T;
        highlighted?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quotes_select".
 */
export interface QuotesSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  validUntil?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  customerUser?: T;
  serviceAddress?:
    | T
    | {
        street1?: T;
        street2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
      };
  propertyType?: T;
  jobSize?: T;
  surfaceDescription?: T;
  soilingLevel?: T;
  accessNotes?: T;
  serviceLines?:
    | T
    | {
        serviceType?: T;
        description?: T;
        quantity?: T;
        unit?: T;
        unitPrice?: T;
        lineTotal?: T;
        taxable?: T;
        taxCategory?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        discountAmount?: T;
        taxDecision?: T;
        taxRatePercent?: T;
        taxDecisionNotes?: T;
        subtotal?: T;
        taxableSubtotal?: T;
        salesTaxAmount?: T;
        total?: T;
      };
  internalNotes?: T;
  sourceSubmission?: T;
  crm?:
    | T
    | {
        provider?: T;
        dealId?: T;
        syncStatus?: T;
        syncedAt?: T;
        syncDetail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  company?: T;
  billingAddress?:
    | T
    | {
        street1?: T;
        street2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
      };
  serviceAddress?:
    | T
    | {
        street1?: T;
        street2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
      };
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invoices_select".
 */
export interface InvoicesSelect<T extends boolean = true> {
  invoiceNumber?: T;
  title?: T;
  status?: T;
  issueDate?: T;
  dueDate?: T;
  customerUser?: T;
  customerEmail?: T;
  customerName?: T;
  serviceAddress?:
    | T
    | {
        street1?: T;
        street2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
      };
  total?: T;
  balanceDue?: T;
  paymentUrl?: T;
  lineItems?:
    | T
    | {
        description?: T;
        amount?: T;
        id?: T;
      };
  relatedQuote?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-plans_select".
 */
export interface ServicePlansSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  anchorDate?: T;
  preferredWindow?: T;
  customerUser?: T;
  customerEmail?: T;
  customerName?: T;
  serviceAddress?:
    | T
    | {
        street1?: T;
        street2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
      };
  sourceQuote?: T;
  serviceSummary?: T;
  singleJobAmount?: T;
  discountPercent?: T;
  visitsPerYear?: T;
  billingInstallmentsPerYear?: T;
  discountedVisitAmount?: T;
  annualPlanAmount?: T;
  installmentAmount?: T;
  cadenceMonths?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-appointments_select".
 */
export interface ServiceAppointmentsSelect<T extends boolean = true> {
  title?: T;
  status?: T;
  arrivalWindow?: T;
  requestSource?: T;
  customerUser?: T;
  customerEmail?: T;
  customerName?: T;
  serviceAddress?:
    | T
    | {
        street1?: T;
        street2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
      };
  requestedDate?: T;
  scheduledStart?: T;
  scheduledEnd?: T;
  relatedQuote?: T;
  servicePlan?: T;
  customerNotes?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "growth-milestones_select".
 */
export interface GrowthMilestonesSelect<T extends boolean = true> {
  title?: T;
  trigger?: T;
  winCondition?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ops-asset-ladder-items_select".
 */
export interface OpsAssetLadderItemsSelect<T extends boolean = true> {
  label?: T;
  buyNotes?: T;
  whyNotes?: T;
  owned?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ops-liability-items_select".
 */
export interface OpsLiabilityItemsSelect<T extends boolean = true> {
  label?: T;
  notes?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ops-scorecard-rows_select".
 */
export interface OpsScorecardRowsSelect<T extends boolean = true> {
  title?: T;
  formula?: T;
  targetGuidance?: T;
  manualValue?: T;
  manualValueLabel?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  leadEmail?: T;
  leadName?: T;
  crmSyncStatus?: T;
  crmSyncedAt?: T;
  crmSyncDetail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  categories?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  posts?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  quotes?:
    | T
    | {
        find?: T;
      };
  footer?:
    | T
    | {
        find?: T;
        update?: T;
      };
  header?:
    | T
    | {
        find?: T;
        update?: T;
      };
  pricing?:
    | T
    | {
        find?: T;
        update?: T;
      };
  quoteSettings?:
    | T
    | {
        find?: T;
        update?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Packages shown when a page uses the “Pricing table” block with “Use global pricing”.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  sectionTitle?: string | null;
  /**
   * Optional intro under the title (plain text).
   */
  sectionIntro?: string | null;
  plans?:
    | {
        /**
         * Package name, e.g. “Driveway refresh”
         */
        name: string;
        /**
         * Short subtitle under the name
         */
        tagline?: string | null;
        /**
         * Display price, e.g. $199, From $149, Call for quote
         */
        price: string;
        /**
         * Fine print: per visit, typical home size, etc.
         */
        priceNote?: string | null;
        highlighted?: boolean | null;
        features?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: number | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Revenue targets and chart copy for the ops command center (portal).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internalOpsSettings".
 */
export interface InternalOpsSetting {
  id: number;
  /**
   * Annual revenue goal in USD (reference for planning; cards use display fields below).
   */
  annualRevenueGoal?: number | null;
  /**
   * Value shown on the “Projected revenue” KPI card (e.g. weighted pipeline target).
   */
  projectedRevenueDisplay?: string | null;
  /**
   * Value shown on the “MRR” KPI card.
   */
  mrrTargetDisplay?: string | null;
  /**
   * Shown under the business momentum chart on /ops.
   */
  chartDisclaimer?: string | null;
  /**
   * Extra line under the chart when HubSpot pipeline is shown (e.g. how open deal totals are computed).
   */
  chartPipelineNote?: string | null;
  /**
   * Help text for the Leads KPI card (info icon on /ops).
   */
  kpiTooltipLeads?: string | null;
  /**
   * Help text for the Quotes KPI card.
   */
  kpiTooltipQuotes?: string | null;
  /**
   * Help text for the Projected revenue KPI card.
   */
  kpiTooltipProjectedRevenue?: string | null;
  /**
   * Help text for the MRR KPI card.
   */
  kpiTooltipMrr?: string | null;
  /**
   * Optional tooltips for scorecard tab rows. KPI name must match the scorecard label exactly (e.g. Revenue, MRR).
   */
  scorecardKpiTooltips?:
    | {
        kpiName: string;
        helpText: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Draft and publish the service toggles, rates, and multipliers that power the public instant quote experience.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quoteSettings".
 */
export interface QuoteSetting {
  id: number;
  /**
   * These rows drive the instant quote cards, labels, and live estimate math. Turn services on/off without code.
   */
  services: {
    serviceKey: 'house_wash' | 'driveway' | 'porch_patio' | 'dock' | 'dumpster_pad';
    label: string;
    description: string;
    recommendedFor: string;
    minimum: number;
    sqftLowRate: number;
    sqftHighRate: number;
    sortOrder?: number | null;
    enabledOnSite?: boolean | null;
    quoteEnabled?: boolean | null;
    frequencyEligible?: boolean | null;
    id?: string | null;
  }[];
  /**
   * How job condition changes the estimate range.
   */
  conditionMultipliers: {
    light: number;
    standard: number;
    heavy: number;
  };
  /**
   * How home height changes the estimate range.
   */
  storyMultipliers: {
    oneStory: number;
    twoStories: number;
    threePlusStories: number;
  };
  /**
   * Discount multipliers for recurring maintenance plans.
   */
  frequencyMultipliers: {
    oneTime: number;
    biannual: number;
    quarterly: number;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Draft and publish the default subscription terms used when Grime Time sells recurring maintenance plans.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicePlanSettings".
 */
export interface ServicePlanSetting {
  id: number;
  /**
   * Default annual visit count for recurring plans.
   */
  minimumVisitsPerYear: number;
  /**
   * Default discount applied to each visit relative to a one-off single-job quote.
   */
  discountPercentOffSingleJob: number;
  /**
   * How many installments the annual plan total is split into by default.
   */
  billingInstallmentsPerYear: number;
  /**
   * Default spacing in months between recurring visits.
   */
  defaultCadenceMonths: number;
  /**
   * Short summary shown to customers in the portal.
   */
  customerSummary?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  sectionTitle?: T;
  sectionIntro?: T;
  plans?:
    | T
    | {
        name?: T;
        tagline?: T;
        price?: T;
        priceNote?: T;
        highlighted?: T;
        features?:
          | T
          | {
              text?: T;
              id?: T;
            };
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "internalOpsSettings_select".
 */
export interface InternalOpsSettingsSelect<T extends boolean = true> {
  annualRevenueGoal?: T;
  projectedRevenueDisplay?: T;
  mrrTargetDisplay?: T;
  chartDisclaimer?: T;
  chartPipelineNote?: T;
  kpiTooltipLeads?: T;
  kpiTooltipQuotes?: T;
  kpiTooltipProjectedRevenue?: T;
  kpiTooltipMrr?: T;
  scorecardKpiTooltips?:
    | T
    | {
        kpiName?: T;
        helpText?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quoteSettings_select".
 */
export interface QuoteSettingsSelect<T extends boolean = true> {
  services?:
    | T
    | {
        serviceKey?: T;
        label?: T;
        description?: T;
        recommendedFor?: T;
        minimum?: T;
        sqftLowRate?: T;
        sqftHighRate?: T;
        sortOrder?: T;
        enabledOnSite?: T;
        quoteEnabled?: T;
        frequencyEligible?: T;
        id?: T;
      };
  conditionMultipliers?:
    | T
    | {
        light?: T;
        standard?: T;
        heavy?: T;
      };
  storyMultipliers?:
    | T
    | {
        oneStory?: T;
        twoStories?: T;
        threePlusStories?: T;
      };
  frequencyMultipliers?:
    | T
    | {
        oneTime?: T;
        biannual?: T;
        quarterly?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "servicePlanSettings_select".
 */
export interface ServicePlanSettingsSelect<T extends boolean = true> {
  minimumVisitsPerYear?: T;
  discountPercentOffSingleJob?: T;
  billingInstallmentsPerYear?: T;
  defaultCadenceMonths?: T;
  customerSummary?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: number | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: number | Post;
        } | null);
    global?: ('quoteSettings' | 'servicePlanSettings') | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}